### ISSUE TITLE
Simplify user apis

### ISSUE THREAD

**Issue by wu-clan** [wu-clan/fastapi_best_architecture#11]
from https://github.com/wu-clan/fastapi_best_architecture/discussions/4#discussioncomment-5655169

**Comment by wu-clan** [comment]
@downdawn 

Which ones should we keep?

login, register, get_userinfo, get_all and more?

**Comment by downdawn** [comment]
> Hi, @downdawn
> 
> Which ones should we keep?
> 
> login, register, get_userinfo, get_all and more?

Email and static files are not necessary here

Retain the basic login, logout, register, delete_user (generally, tombstone, is_delete or is_active), get_all_users, userinfo.

The corresponding User model can also be simplified, wechat, qq, blog_address, introduction are also unnecessary

In addition to user, we can add permission-related interfaces

If we really make a project similar to go-admin in the future, we will add relevant interfaces.

**Comment by wu-clan** [comment]
I prefer [gin-vue-admin](https://github.com/flipped-aurora/gin-vue-admin)

**Comment by downdawn** [comment]
> I prefer [gin-vue-admin](https://github.com/flipped-aurora/gin-vue-admin)

nice
